Update ps2.yml

diff --git a/.github/workflows/ps2.yml b/.github/workflows/ps2.yml
--- a/.github/workflows/ps2.yml
+++ b/.github/workflows/ps2.yml
@@ -33,14 +33,9 @@ jobs:
               ln -sf \$PS2DEV/ee/bin/mips64r5900el-ps2-elf-ar /usr/local/bin/ee-ar
 
               # 3. SELECTIVE GHOSTING
-              # We ghost everything EXCEPT the core Capcom/CPS2 files
               echo 'void ghost_stub(void) {}' > /tmp/ghost.c
               for d in \$(find src -type d -name 'drivers' -o -name 'vidhrdw' -o -name 'sndhrdw'); do
-                find \"\$d\" -name '*.c' \
-                  ! -name 'cps2.c' \
-                  ! -name 'capcom.c' \
-                  ! -name 'common.c' \
-                  -exec cp /tmp/ghost.c {} \;
+                find \"\$d\" -name '*.c' ! -name 'cps2.c' ! -name 'capcom.c' ! -name 'common.c' -exec cp /tmp/ghost.c {} \;
               done
               
               # 4. OVERWRITE THE DRIVER LIST
@@ -52,39 +47,39 @@ jobs:
               printf '#include <setjmp.h>\n#include <stdlib.h>\n#include \"libco.h\"\ntypedef struct { jmp_buf context; } sjlj_thread_t;\nstatic sjlj_thread_t *co_running = NULL;\ncothread_t co_active(void) { if(!co_running) { static sjlj_thread_t m; co_running = &m; } return (cothread_t)co_running; }\ncothread_t co_create(unsigned int s, void (*e)(void)) { return (cothread_t)malloc(sizeof(sjlj_thread_t)); }\nvoid co_delete(cothread_t c) { free(c); }\nvoid co_switch(cothread_t n) { sjlj_thread_t *next = (sjlj_thread_t*)n; sjlj_thread_t *prev = co_running; co_running = next; if(!setjmp(prev->context)) longjmp(next->context, 1); }' > \$CO_DIR/sjlj.c
               cp \$CO_DIR/sjlj.c \$CO_DIR/libco.c
 
-              # 6. COMPREHENSIVE GLUE FILE
+              # 6. GLUE FILE
               echo '
               #include <stdio.h>
               #include <stddef.h>
               #include <stdbool.h>
-              size_t spriteram_size = 0;
-              size_t spriteram_2_size = 0;
-              unsigned char *spriteram = NULL;
-              unsigned char *buffered_spriteram = NULL;
-              unsigned char *spriteram_2 = NULL;
-              unsigned char *buffered_spriteram_2 = NULL;
-              unsigned char *CinemaVectorData = NULL;
+              size_t spriteram_size = 0, spriteram_2_size = 0;
+              unsigned char *spriteram = NULL, *buffered_spriteram = NULL, *spriteram_2 = NULL, *buffered_spriteram_2 = NULL, *CinemaVectorData = NULL;
               float vector_get_intensity(void) { return 1.0f; }
               void vector_set_intensity(float i) { }
               void path_basedir(char *path) { if (path) path[0] = 0; }
               bool path_mkdir(const char *dir) { return true; }
               extern int run_game(int game_index); 
-              int main(int argc, char *argv[]) {
-                  return run_game(0); 
-              }' > ps2_main.c
+              int main(int argc, char *argv[]) { return run_game(0); }' > ps2_main.c
 
               # 7. BUILD
               make platform=ps2 clean
-              # Explicitly define CPS2 to ensure the driver is compiled in
               make platform=ps2 CC='ee-gcc -fno-lto -DCPS2' AR=ee-ar -j\$(nproc)
-              
-              # Compile our glue
               ee-gcc -fno-lto -c ps2_main.c -o ps2_main.o -Isrc -Isrc/ps2 -Isrc/libretro/libretro-common/include
 
-              # 8. FINAL LINK (Explicitly adding the CPS2 object just in case)
+              # 8. IMPROVED SEARCH FOR OBJECTS
               REAL_CRT0=\$(find \$PS2DEV -name 'crt0.o' | head -n 1)
               REAL_LINKFILE=\$(find \$PS2DEV -name 'linkfile' | head -n 1)
-              CPS2_OBJ=\$(find obj -name 'cps2.o' | head -n 1)
+              
+              # Search specifically for the cps2 object within the current build dir
+              CPS2_OBJ=\$(find . -name 'cps2.o' | head -n 1)
+              
+              echo \"Linker Debug: CRT0=\$REAL_CRT0, LINK=\$REAL_LINKFILE, CPS2=\$CPS2_OBJ\"
+
+              # Link only if the required object was found
+              if [ -z \"\$CPS2_OBJ\" ]; then
+                echo \"FATAL: cps2.o not found. Compilation might have failed.\"
+                exit 1
+              fi
 
               echo '--- LINKING AVP.ELF ---'
               ee-gcc -fno-lto -T\"\$REAL_LINKFILE\" \
