Update ps2.yml

diff --git a/.github/workflows/ps2.yml b/.github/workflows/ps2.yml
--- a/.github/workflows/ps2.yml
+++ b/.github/workflows/ps2.yml
@@ -20,10 +20,8 @@ jobs:
             sh -c "
               set -e
 
-              # 1. INSTALL TOOLS
+              # 1. TOOLS & PATHS
               apk add --no-cache build-base git make
-
-              # 2. TOOLCHAIN & PATHS
               export PS2DEV=/usr/local/ps2dev
               export PS2SDK=\$PS2DEV/ps2sdk
               export PATH=\$PATH:\$PS2DEV/bin:\$PS2DEV/ee/bin:\$PS2SDK/bin
@@ -32,70 +30,62 @@ jobs:
               ln -sf \$PS2DEV/ee/bin/mips64r5900el-ps2-elf-g++ /usr/local/bin/ee-g++
               ln -sf \$PS2DEV/ee/bin/mips64r5900el-ps2-elf-ar /usr/local/bin/ee-ar
 
-              # 3. SELECTIVE GHOSTING
+              # 2. GHOSTING
               echo 'void ghost_stub(void) {}' > /tmp/ghost.c
               for d in \$(find src -type d -name 'drivers' -o -name 'vidhrdw' -o -name 'sndhrdw'); do
-                find \"\$d\" -name '*.c' \
-                  ! -name 'cps2.c' \
-                  ! -name 'capcom.c' \
-                  ! -name 'common.c' \
-                  -exec cp /tmp/ghost.c {} \;
+                find \"\$d\" -name '*.c' ! -name 'cps2.c' ! -name 'capcom.c' ! -name 'common.c' -exec cp /tmp/ghost.c {} \;
               done
               
-              # 4. OVERWRITE THE DRIVER LIST
+              # 3. DRIVER LIST
               printf '#include \"driver.h\"\nextern struct GameDriver driver_avp;\nconst struct GameDriver *drivers[] = { &driver_avp, 0 };\n' > src/driver.c
 
-              # 5. FIX LIBCO
-              CO_DIR='src/libretro/libretro-common/libco'
-              mkdir -p \$CO_DIR
-              printf '#include <setjmp.h>\n#include <stdlib.h>\n#include \"libco.h\"\ntypedef struct { jmp_buf context; } sjlj_thread_t;\nstatic sjlj_thread_t *co_running = NULL;\ncothread_t co_active(void) { if(!co_running) { static sjlj_thread_t m; co_running = &m; } return (cothread_t)co_running; }\ncothread_t co_create(unsigned int s, void (*e)(void)) { return (cothread_t)malloc(sizeof(sjlj_thread_t)); }\nvoid co_delete(cothread_t c) { free(c); }\nvoid co_switch(cothread_t n) { sjlj_thread_t *next = (sjlj_thread_t*)n; sjlj_thread_t *prev = co_running; co_running = next; if(!setjmp(prev->context)) longjmp(next->context, 1); }' > \$CO_DIR/sjlj.c
-              cp \$CO_DIR/sjlj.c \$CO_DIR/libco.c
-
-              # 6. COMPREHENSIVE GLUE FILE
+              # 4. GLUE CODE
               echo '
               #include <stdio.h>
               #include <stddef.h>
               #include <stdbool.h>
-              size_t spriteram_size = 0;
-              size_t spriteram_2_size = 0;
-              unsigned char *spriteram = NULL;
-              unsigned char *buffered_spriteram = NULL;
-              unsigned char *spriteram_2 = NULL;
-              unsigned char *buffered_spriteram_2 = NULL;
-              unsigned char *CinemaVectorData = NULL;
+              size_t spriteram_size = 0, spriteram_2_size = 0;
+              unsigned char *spriteram = NULL, *buffered_spriteram = NULL, *spriteram_2 = NULL, *buffered_spriteram_2 = NULL, *CinemaVectorData = NULL;
               float vector_get_intensity(void) { return 1.0f; }
               void vector_set_intensity(float i) { }
               void path_basedir(char *path) { if (path) path[0] = 0; }
               bool path_mkdir(const char *dir) { return true; }
               extern int run_game(int game_index); 
-              int main(int argc, char *argv[]) {
-                  return run_game(0); 
-              }' > ps2_main.c
+              int main(int argc, char *argv[]) { return run_game(0); }' > ps2_main.c
 
-              # 7. BUILD
+              # 5. THE BUILD
               make platform=ps2 clean
               make platform=ps2 CC='ee-gcc -fno-lto -DCPS2' AR=ee-ar -j\$(nproc)
               
+              # 6. DIAGNOSTIC: FIND THE OBJECT
+              echo '--- LOCATING OBJECTS ---'
+              # We search the whole tree and copy it to the root immediately
+              ACTUAL_CPS2=\$(find . -name 'cps2.o' | head -n 1)
+              if [ -n \"\$ACTUAL_CPS2\" ]; then
+                echo \"Found cps2.o at: \$ACTUAL_CPS2\"
+                cp \"\$ACTUAL_CPS2\" ./cps2_found.o
+              else
+                echo \"CRITICAL: cps2.o still missing after build.\"
+                # List all .o files to see what the Makefile is actually doing
+                find . -name '*.o' | head -n 20
+                exit 1
+              fi
+
+              # 7. GLUE COMPILE
               ee-gcc -fno-lto -c ps2_main.c -o ps2_main.o -Isrc -Isrc/ps2 -Isrc/libretro/libretro-common/include
 
               # 8. FINAL LINK
-              REAL_CRT0=\$(find \$PS2DEV -name 'crt0.o' | head -n 1)
-              REAL_LINKFILE=\$(find \$PS2DEV -name 'linkfile' | head -n 1)
+              CRT0=\$(find \$PS2DEV -name 'crt0.o' | head -n 1)
+              LNK=\$(find \$PS2DEV -name 'linkfile' | head -n 1)
               
-              # Looking for the object file wherever the Makefile put it
-              CPS2_OBJ=\$(find . -name 'cps2.o' | head -n 1)
-
               echo '--- LINKING AVP.ELF ---'
-              # If CPS2_OBJ is empty, the linker will error; we check for it here
-              if [ -z \"\$CPS2_OBJ\" ]; then echo \"cps2.o not found\"; exit 1; fi
-
-              ee-gcc -fno-lto -T\"\$REAL_LINKFILE\" \
+              ee-gcc -fno-lto -T\"\$LNK\" \
                 -L\"\$PS2SDK/ee/lib\" \
-                -L\$(dirname \"\$REAL_CRT0\") \
+                -L\$(dirname \"\$CRT0\") \
                 -o AVP.ELF \
-                \"\$REAL_CRT0\" \
+                \"\$CRT0\" \
                 ps2_main.o \
-                \"\$CPS2_OBJ\" \
+                ./cps2_found.o \
                 mame2000_libretro_ps2.a \
                 -lpatches -ldebug -lstdc++ -lc -lm -lkernel -Wl,-z,muldefs
               
